#!/bin/bash

source $wm/style.sh
bspc monitor -d "1/"
bspc config window_gap $window_gap

bspc config split_ratio $split_ratio
bspc config bottom_padding $(expr $bar_padding + $window_gap)

bspc config border_width $border_width
bspc config focused_border_color $magenta
bspc config normal_border_color $bg

$tools/bar.sh -y 1440
